// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6UkmUmkiJ9vqGTD9TvW4tsL3FehmgD3w',
    appId: '1:627500478888:web:fc34331b5bab596e1eed9d',
    messagingSenderId: '627500478888',
    projectId: 'goodproject-3a698',
    authDomain: 'goodproject-3a698.firebaseapp.com',
    storageBucket: 'goodproject-3a698.appspot.com',
    measurementId: 'G-KEZ9WW6FMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkEPzZ9PJaHuCm6j1rDavemZj3-J4VYU',
    appId: '1:627500478888:android:1ff19c0a448c8afd1eed9d',
    messagingSenderId: '627500478888',
    projectId: 'goodproject-3a698',
    storageBucket: 'goodproject-3a698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAKCGtxVg3SbgTMFDopnoe5rpLfso1284',
    appId: '1:627500478888:ios:20e290925bd5162c1eed9d',
    messagingSenderId: '627500478888',
    projectId: 'goodproject-3a698',
    storageBucket: 'goodproject-3a698.appspot.com',
    iosBundleId: 'com.example.goodproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAKCGtxVg3SbgTMFDopnoe5rpLfso1284',
    appId: '1:627500478888:ios:e2f60cbe5f45b9dc1eed9d',
    messagingSenderId: '627500478888',
    projectId: 'goodproject-3a698',
    storageBucket: 'goodproject-3a698.appspot.com',
    iosBundleId: 'com.example.goodproject.RunnerTests',
  );
}
